"""add phase 2 analytical models

Revision ID: a8544894009f
Revises: 20260727_0001
Create Date: 2026-07-27 15:19:24.937564
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a8544894009f'
down_revision: str | None = '20260727_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=180), nullable=False),
    sa.Column('normalized_name', sa.String(length=180), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('primary_position', sa.String(length=80), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', name='uq_player_external_id')
    )
    op.create_index(op.f('ix_player_normalized_name'), 'player', ['normalized_name'], unique=False)
    op.create_table('statistical_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_statistical_config_key')
    )
    op.create_index(op.f('ix_statistical_config_key'), 'statistical_config', ['key'], unique=False)
    op.create_table('player_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('alias', sa.String(length=180), nullable=False),
    sa.Column('normalized_alias', sa.String(length=180), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'normalized_alias', name='uq_player_alias_source_normalized')
    )
    op.create_index(op.f('ix_player_alias_normalized_alias'), 'player_alias', ['normalized_alias'], unique=False)
    op.create_index(op.f('ix_player_alias_player_id'), 'player_alias', ['player_id'], unique=False)
    op.create_table('player_team_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'team_id', 'season_id', 'start_date', name='uq_player_team_history_period')
    )
    op.create_index(op.f('ix_player_team_history_player_id'), 'player_team_history', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_team_history_season_id'), 'player_team_history', ['season_id'], unique=False)
    op.create_index(op.f('ix_player_team_history_team_id'), 'player_team_history', ['team_id'], unique=False)
    op.create_table('team_form_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('matches_considered', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('home_goals_for_average', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('home_goals_against_average', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('away_goals_for_average', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('away_goals_against_average', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('clean_sheet_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('over_25_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('btts_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'competition_id', 'season_id', 'snapshot_date', 'matches_considered', name='uq_team_form_snapshot_identity')
    )
    op.create_index(op.f('ix_team_form_snapshot_competition_id'), 'team_form_snapshot', ['competition_id'], unique=False)
    op.create_index(op.f('ix_team_form_snapshot_season_id'), 'team_form_snapshot', ['season_id'], unique=False)
    op.create_index(op.f('ix_team_form_snapshot_snapshot_date'), 'team_form_snapshot', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_team_form_snapshot_team_id'), 'team_form_snapshot', ['team_id'], unique=False)
    op.create_table('team_goal_timing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('venue_type', sa.String(length=20), nullable=False),
    sa.Column('interval_start', sa.Integer(), nullable=True),
    sa.Column('interval_end', sa.Integer(), nullable=True),
    sa.Column('goals_scored', sa.Integer(), nullable=False),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('percentage_scored', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('percentage_conceded', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'competition_id', 'season_id', 'venue_type', 'interval_start', 'interval_end', 'calculated_at', name='uq_team_goal_timing_interval')
    )
    op.create_index(op.f('ix_team_goal_timing_calculated_at'), 'team_goal_timing', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_team_goal_timing_competition_id'), 'team_goal_timing', ['competition_id'], unique=False)
    op.create_index(op.f('ix_team_goal_timing_season_id'), 'team_goal_timing', ['season_id'], unique=False)
    op.create_index(op.f('ix_team_goal_timing_team_id'), 'team_goal_timing', ['team_id'], unique=False)
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('supporting_data', sa.JSON(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('reliability', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'alert_type', 'created_at', name='uq_alert_match_type_created')
    )
    op.create_index(op.f('ix_alert_created_at'), 'alert', ['created_at'], unique=False)
    op.create_index(op.f('ix_alert_match_id'), 'alert', ['match_id'], unique=False)
    op.create_table('analysis_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reliability', sa.String(length=40), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'analysis_type', 'calculated_at', name='uq_analysis_result_capture')
    )
    op.create_index(op.f('ix_analysis_result_calculated_at'), 'analysis_result', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_analysis_result_match_id'), 'analysis_result', ['match_id'], unique=False)
    op.create_table('lineup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('position', sa.String(length=80), nullable=True),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id', 'player_id', 'source', name='uq_lineup_player_source')
    )
    op.create_index(op.f('ix_lineup_captured_at'), 'lineup', ['captured_at'], unique=False)
    op.create_index(op.f('ix_lineup_match_id'), 'lineup', ['match_id'], unique=False)
    op.create_index(op.f('ix_lineup_player_id'), 'lineup', ['player_id'], unique=False)
    op.create_index(op.f('ix_lineup_team_id'), 'lineup', ['team_id'], unique=False)
    op.create_table('player_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=240), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'match_id', 'source', name='uq_player_availability_source')
    )
    op.create_index(op.f('ix_player_availability_match_id'), 'player_availability', ['match_id'], unique=False)
    op.create_index(op.f('ix_player_availability_player_id'), 'player_availability', ['player_id'], unique=False)
    op.create_table('player_match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opponent_team_id', sa.Integer(), nullable=False),
    sa.Column('stadium_id', sa.Integer(), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('position_played', sa.String(length=80), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('key_passes', sa.Integer(), nullable=True),
    sa.Column('expected_goals', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('expected_assists', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('rating', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('was_home_team', sa.Boolean(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['opponent_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadium.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'match_id', 'source', name='uq_player_match_stats_source')
    )
    op.create_index(op.f('ix_player_match_stats_captured_at'), 'player_match_stats', ['captured_at'], unique=False)
    op.create_index(op.f('ix_player_match_stats_competition_id'), 'player_match_stats', ['competition_id'], unique=False)
    op.create_index(op.f('ix_player_match_stats_match_id'), 'player_match_stats', ['match_id'], unique=False)
    op.create_index(op.f('ix_player_match_stats_opponent_team_id'), 'player_match_stats', ['opponent_team_id'], unique=False)
    op.create_index(op.f('ix_player_match_stats_player_id'), 'player_match_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_match_stats_season_id'), 'player_match_stats', ['season_id'], unique=False)
    op.create_index(op.f('ix_player_match_stats_stadium_id'), 'player_match_stats', ['stadium_id'], unique=False)
    op.create_index(op.f('ix_player_match_stats_team_id'), 'player_match_stats', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_match_stats_team_id'), table_name='player_match_stats')
    op.drop_index(op.f('ix_player_match_stats_stadium_id'), table_name='player_match_stats')
    op.drop_index(op.f('ix_player_match_stats_season_id'), table_name='player_match_stats')
    op.drop_index(op.f('ix_player_match_stats_player_id'), table_name='player_match_stats')
    op.drop_index(op.f('ix_player_match_stats_opponent_team_id'), table_name='player_match_stats')
    op.drop_index(op.f('ix_player_match_stats_match_id'), table_name='player_match_stats')
    op.drop_index(op.f('ix_player_match_stats_competition_id'), table_name='player_match_stats')
    op.drop_index(op.f('ix_player_match_stats_captured_at'), table_name='player_match_stats')
    op.drop_table('player_match_stats')
    op.drop_index(op.f('ix_player_availability_player_id'), table_name='player_availability')
    op.drop_index(op.f('ix_player_availability_match_id'), table_name='player_availability')
    op.drop_table('player_availability')
    op.drop_index(op.f('ix_lineup_team_id'), table_name='lineup')
    op.drop_index(op.f('ix_lineup_player_id'), table_name='lineup')
    op.drop_index(op.f('ix_lineup_match_id'), table_name='lineup')
    op.drop_index(op.f('ix_lineup_captured_at'), table_name='lineup')
    op.drop_table('lineup')
    op.drop_index(op.f('ix_analysis_result_match_id'), table_name='analysis_result')
    op.drop_index(op.f('ix_analysis_result_calculated_at'), table_name='analysis_result')
    op.drop_table('analysis_result')
    op.drop_index(op.f('ix_alert_match_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_created_at'), table_name='alert')
    op.drop_table('alert')
    op.drop_index(op.f('ix_team_goal_timing_team_id'), table_name='team_goal_timing')
    op.drop_index(op.f('ix_team_goal_timing_season_id'), table_name='team_goal_timing')
    op.drop_index(op.f('ix_team_goal_timing_competition_id'), table_name='team_goal_timing')
    op.drop_index(op.f('ix_team_goal_timing_calculated_at'), table_name='team_goal_timing')
    op.drop_table('team_goal_timing')
    op.drop_index(op.f('ix_team_form_snapshot_team_id'), table_name='team_form_snapshot')
    op.drop_index(op.f('ix_team_form_snapshot_snapshot_date'), table_name='team_form_snapshot')
    op.drop_index(op.f('ix_team_form_snapshot_season_id'), table_name='team_form_snapshot')
    op.drop_index(op.f('ix_team_form_snapshot_competition_id'), table_name='team_form_snapshot')
    op.drop_table('team_form_snapshot')
    op.drop_index(op.f('ix_player_team_history_team_id'), table_name='player_team_history')
    op.drop_index(op.f('ix_player_team_history_season_id'), table_name='player_team_history')
    op.drop_index(op.f('ix_player_team_history_player_id'), table_name='player_team_history')
    op.drop_table('player_team_history')
    op.drop_index(op.f('ix_player_alias_player_id'), table_name='player_alias')
    op.drop_index(op.f('ix_player_alias_normalized_alias'), table_name='player_alias')
    op.drop_table('player_alias')
    op.drop_index(op.f('ix_statistical_config_key'), table_name='statistical_config')
    op.drop_table('statistical_config')
    op.drop_index(op.f('ix_player_normalized_name'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
